config/routes.rb
Rails.application.routes.draw do

  # Establish route URL to these controller/view
  get 'main/home'
  get 'main/about'
  get 'main/contact'

 # Standardise the related routes below
  get 'user/signup', to: 'users#signup'
  get 'user/login', to: 'sessions#login'
  get 'user/account', to: 'users#account'
  get 'user/logout', to: 'sessions#destroy'
  get 'user/edit', to: 'users#edit'

  delete 'remove_item', to: 'items#remove_item'

  get 'checkout/details', to: 'customer_infos#new'
  get 'checkout/details/order', to: 'orders#new'

  # Contact form that uses mailer to send email (if it was linked to SMTP server)
  get 'contacts/form'

  # Reroutes contacts_request_form to request_form - used for POST method only
  post 'request_form', to:'contacts#request_form'

  # Get all the appropriate CRUD paths/routes for our resources
  resources :users, only: [:create, :edit, :update, :signup, :account]
  resources :sessions, only: [:create, :login, :destroy]
  # User Reviews should be nested to products (as reviews should be created on products)
  resources :products, only: [:index, :show] do
    resources :reviews, only: [:new]
  end

  resources :reviews, only: [:index, :show, :edit, :destroy, :create, :update]

  resources :baskets, only: [:index, :show, :create, :destroy]
  resources :items, only: [:index, :create, :remove_item]
  resources :orders, only: [:index, :show, :new, :create]
  resources :customer_infos, only: [:index, :show, :new, :edit, :create, :update]

  # This is the first page the user will first load into as it is the root page
  root 'main#home'

  # We don't want those pesky unknown routes disturbing our user experience - redirects all unknown routes to root_path
  match '*path' => redirect('/'), via: :get
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/basket.rb
class Basket < ApplicationRecord
  has_many :items, dependent: :destroy
  belongs_to :customer_info, optional: true
  has_one :order
end

app/controllers/baskets_controller.rb
class BasketsController < ApplicationController
  before_action :set_basket, only: [:show, :edit, :update, :destroy]

  # GET /baskets
  # GET /baskets.json
  def index
    # Only an admin account can access this page
    if session[:user_id] != 0
      flash[:alert] = "Please add an item to your basket first."
      redirect_to root_path
    else
      @baskets = Basket.all
    end
  end

  # GET /baskets/1
  # GET /baskets/1.json
  def show
    if Basket.exists?(session[:basket_id]) && session[:basket_id] != nil
      # We only want to check the id, so we just call the id column only
      @sessionBasket = Basket.select(:id).find(session[:basket_id])
      # This checks if the session basket id matches the basket id
      # We don't want other people accessing each other's baskets!
      if !(@sessionBasket.id == @basket.id)
        flash[:alert] = "Basket id does not match your session id."
        redirect_to root_path
      end
    else
      flash[:alert] = "Could not find Basket Session id."
      redirect_to root_path
    end
  end

  # POST /baskets
  # POST /baskets.json
  def create
    @basket = Basket.new(basket_params)
    respond_to do |format|
      if @basket.save
        format.html { redirect_to @basket, notice: 'Basket was successfully created.' }
        format.json { render :show, status: :created, location: @basket }
      else
        format.html { render :new }
        format.json { render json: @basket.errors, status: :unprocessable_entity }
      end
    end
  end


  # DELETE /baskets/1
  # DELETE /baskets/1.json
  def destroy
    @basket.destroy
    respond_to do |format|
      format.html { redirect_to baskets_url, notice: 'Basket was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_basket
      if params[:id] != nil && Basket.exists?(params[:id])
        @basket = Basket.find(params[:id])
      else
        params[:id] = nil
      end
    end

    # Only allow a list of trusted parameters through.
    def basket_params
      params.require(:basket).permit(:customer_info_id, :customerName, :address, :city, :county, :postcode)
    end

end

app/helpers/baskets_helper.rb
module BasketsHelper
end

app/views/baskets/index.html.erb
<h1><%=t('.index_title')%></h1>
<hr>

<div class="container">
  <br>
  <div class="row">
    <div class="col-sm-2" align="center">
      <span>
        <b><%=t('.index_basket_column')%></b>
      </span>
    </div>
    <div class="col-sm-2" align="center">
      <span>
        <b><%=t('.index_customerInfo_column')%></b>
      </span>
    </div>
    <div class="col-sm-2" align="center">
      <span>
        <b><%=t('.index_items_column')%></b>
      </span>
    </div>
    <div class="col-sm-2" align="center"></div>
  </div>
  <hr>
  <% @baskets.each do |basket| %>
    <div class="row">
      <div class="col-sm-2" align="center">
        <%= basket.id %>
      </div>

      <div class="col-sm-2" align="center">
        <%= basket.customer_info_id %>
      </div>

      <div class="col-sm-2" align="center">
        <%= basket.items.count %>
      </div>

      <div class="col-sm-2">
        <%= link_to t('.index_destroy_button'), basket, method: :delete, data: { confirm: t('.index_destroy_message') } %>
      </div>
    </div>
    <hr>
  <% end %>
</div>

app/views/baskets/show.html.erb
<%= render 'shared/flashmessage' %>

<div class="container">
  <br>
  <div class="row">
    <div class="col-sm-1" align="center">
      <span>
        <b><%=t('.show_image_column')%></b>
      </span>
    </div>
    <div class="col-sm-4" align="center">
      <span>
        <b><%=t('.show_productname_column')%></b>
      </span>
    </div>
    <div class="col-sm-2" align="center">
      <span>
        <b><%=t('.show_price')%></b>
      </span>
    </div>
    <div class="col-sm-2" align="center">
      <span>
        <b><%=t('.show_quantity_column')%></b>
      </span>
    </div>
  </div>
  <hr>
  <% totalPrice = 0 %>
    <% @basket.items.each do |item| %>
      <div class="row">
        <div class="col-sm-1" align="center">
          <a href="<%= products_path(@product) %>"><img src="<%= asset_path(item.product.image_url)%>" alt="<%= item.product.name %>" class="img-icon"></a>
        </div>

        <div class="col-sm-4" align="center">
          <h4><%= link_to item.product.name, item.product, class: "vertical-align-text" %></h4>
        </div>

        <div class="col-sm-2" align="center">
          <h4>
            <span class="vertical-align-text"><%=t('.show_currency')%><%= item.product.price %></span></h4>
        </div>

        <div class="col-sm-2" align="center">
          <h4>
            <span class="vertical-align-text"><%= item.quantityOrdered %></span></h4>
        </div>

        <div class="col-sm-2 vertical-align-text" align="center">
          <%= button_to 'Remove', remove_item_url(params: { id: item.id}), method: :delete, class: "btn btn-danger" %>
        </div>
        <% totalPrice += item.product.price %>
        </div>
        <hr>
      <% end %>
      <div class="row">
        <div class="col-sm-1" align="center">
          <%= link_to 'Back', products_path %>
        </div>
        <div class="col-sm-4" align="center">
          <h4><%=t('.show_totalitems_column')%>
            <%= @basket.items.count %></h4>
        </div>
        <div class="col-sm-2" align="center">
          <h4><%=t('.show_total_column')%>
            <%=t('.show_currency')%><%= totalPrice %></h4>
        </div>
        <div class="col-sm-2" align="center">
          <%= button_to t('.show_checkout_button'), checkout_details_path(), method: :get, class: "btn btn-primary" %>
        </div>
      </div>
      <br>
    </div>