config/routes.rb
Rails.application.routes.draw do

  # Establish route URL to these controller/view
  get 'main/home'
  get 'main/about'
  get 'main/contact'

 # Standardise the related routes below
  get 'user/signup', to: 'users#signup'
  get 'user/login', to: 'sessions#login'
  get 'user/account', to: 'users#account'
  get 'user/logout', to: 'sessions#destroy'
  get 'user/edit', to: 'users#edit'

  delete 'remove_item', to: 'items#remove_item'

  get 'checkout/details', to: 'customer_infos#new'
  get 'checkout/details/order', to: 'orders#new'

  # Contact form that uses mailer to send email (if it was linked to SMTP server)
  get 'contacts/form'

  # Reroutes contacts_request_form to request_form - used for POST method only
  post 'request_form', to:'contacts#request_form'

  # Get all the appropriate CRUD paths/routes for our resources
  resources :users, only: [:create, :edit, :update, :signup, :account]
  resources :sessions, only: [:create, :login, :destroy]
  # User Reviews should be nested to products (as reviews should be created on products)
  resources :products, only: [:index, :show] do
    resources :reviews, only: [:new]
  end

  resources :reviews, only: [:index, :show, :edit, :destroy, :create, :update]

  resources :baskets, only: [:index, :show, :create, :destroy]
  resources :items, only: [:index, :create, :remove_item]
  resources :orders, only: [:index, :show, :new, :create]
  resources :customer_infos, only: [:index, :show, :new, :edit, :create, :update]

  # This is the first page the user will first load into as it is the root page
  root 'main#home'

  # We don't want those pesky unknown routes disturbing our user experience - redirects all unknown routes to root_path
  match '*path' => redirect('/'), via: :get
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/basket.rb
class Basket < ApplicationRecord
  has_many :items, dependent: :destroy
  belongs_to :customer_info, optional: true
  has_one :order
end

app/models/customer_info.rb
class CustomerInfo < ApplicationRecord
  belongs_to :user, optional: true
  has_many :baskets

  validates :customerName, presence: true
  validates :telephone, presence: true
  validates :address, presence: true
  validates :city, presence: true
  validates :county, presence: true
  validates :postcode, presence: true
end

app/models/item.rb
class Item < ApplicationRecord
  # The intermediary table between basket and product
  belongs_to :basket
  belongs_to :product
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :basket

  validates :card_number, presence: true
  validates :svc_number, presence: true
end

app/models/product.rb
class Product < ApplicationRecord
  # Ensures the Price field can only be >= £0 - So third-party listings cannot be free (if this feature is implemented)
  validates :price, numericality: {greater_than_or_equal_to: 0}
  has_many :items, dependent: :restrict_with_error
  has_many :reviews
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :product
  belongs_to :user

  validates :title, presence: true
  validates :comment, presence: true
  validates :rating, numericality: {greater_than_or_equal_to: 0, less_than_or_equal_to: 5}, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Hash and salt passwords using bcrypt hash algorithm methods
  has_secure_password
  # A user can only have one customer record
  has_one :customer_info
  has_many :reviews
  #validates_uniqueness_of :username, :email
  validates :username, presence: true, uniqueness: true
  validates :email, presence: true, uniqueness: true
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:show, :edit, :update, :destroy]
  # Create a basket before adding in a Product item
  before_action :set_basket, only: [:create]

  # GET /items
  # GET /items.json
  def index
    if session[:user_id] != 0
      flash[:alert] = "You do not have permission to access this page."
      redirect_to root_path
    else
      @items = Item.all
    end
  end

  # POST /items
  # POST /items.json
  def create
    # The product id is sent from the product show page using the Buy button
    product = Product.find(params[:product_id])
    quantity = params[:quantityOrdered]

    respond_to do |format|
      if product.quantityInStock > 0
        @item = @basket.items.build(product: product, quantityOrdered: quantity)

        if @item.save
          format.html { redirect_to @item.basket, flash: {notice: 'Item was successfully added.' }}
          format.json { render :show, status: :created, location: @item }
          # Reduce the stock quantity of the current product by 1 (as you can only add one product to the basket at a time)
          product.quantityInStock -= 1
          product.save
        else
          format.html { redirect_to @item.basket, flash: {alert: 'Something went wrong: Item could not be added.' }}
          format.json { render json: @item.errors, status: :unprocessable_entity }
        end
      else
        format.html { redirect_to product, flash: {alert: 'Cannot add item as it is out of stock.'}}
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  def remove_item
    @item = Item.find(params[:id])
    product = Product.find(@item.product_id)

    if Basket.exists?(session[:basket_id]) && session[:basket_id] != nil
      @basket = Basket.find(session[:basket_id])
      @item.destroy
      # Increment the stock quantity of the current product by 1 (as you can only remove 1 product at a time)
      product.quantityInStock += 1
      product.save

      flash[:notice] = "Item was successfully removed."
      redirect_to @basket
    else
      flash[:alert] = "Could not find Basket Session id."
      redirect_to root_path
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def item_params
      params.require(:item).permit(:basket_id, :product_id, :quantityOrdered)
    end

    # Check if basket is available to user or not
    def set_basket
      # Check if the current basket id session matches a record in the Basket table and that it is not nil
      if Basket.exists?(session[:basket_id]) && session[:basket_id] != nil
        @basket = Basket.find(session[:basket_id])
        session[:basket_id] = @basket.id
      else
        # else create a new basket for a new session
        if user_logged_in
          if CustomerInfo.exists?(user_id: session[:user_id])
            @customerInfo = CustomerInfo.find_by user_id: session[:user_id]
            @basket = Basket.create(customer_info_id: @customerInfo.id)
            session[:basket_id] = @basket.id
          else
            @basket = Basket.create
            session[:basket_id] = @basket.id
          end
        else
          @basket = Basket.create
          session[:basket_id] = @basket.id
        end
      end
    end
  end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def home
    # Render all the products on the home page
    @products = Product.all
  end

  def contact
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/baskets_helper.rb
module BasketsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Whamazone</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%# include stylesheets/application.scss and javascripts/application.js %>
      <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
      <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    </head>

    <body>
      <div id="wrapper">
        <%= render 'shared/header' %>
        <div class="margin-padding">
          <%= yield %>
        </div>
        <%= render 'shared/footer' %>
      </div>
    </body>
  </html>

app/views/shared/_badgechoice.html.erb
<span class="badge badge-secondary" title="<%=t('.badge_title')%>">
  <font class="brand-color"><%=t('.badge_company')%></font>
  <%=t('.badge_name')%></span>

app/views/shared/_badgenew.html.erb
<span class="badge badge-danger"><%=t('.badge_title')%></span>

app/views/shared/_banner.html.erb
<div class="alert alert-info alert-dismissible fade show" role="alert">
  <strong><%=t('.banner_message_of_the_day')%></strong> <a id = home_banner></a>
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>

app/views/shared/_flashmessage.html.erb
<%# For each message loaded into the flash container
Output each message in HTML for the user can see in the view %>
  <% flash.each do |flash_type, content| %>
    <% if flash_type == "notice" %>
      <div class="alert alert-success alert-dismissible fade show" role="alert">
        <%= content %>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
    <% else %>
      <div class="alert alert-danger alert-dismissible fade show" role="alert">
        <%= content %>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
    <% end %>
  <% end %>

app/views/shared/_footer.html.erb
<footer class="footer">
  <div class="footer-copyright text-center">
       <a id="author"> <%=t('footer_author')%> </a> 
  </div>
</footer>

app/views/shared/_header.html.erb
<%# Parial view for a header for every view page
Inserted into the application.html.erb file %>

  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <a class="navbar-brand" href="<%= root_path %>"><%=t('.header_company')%></a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link" href="<%= root_path %>"><%=t('.header_home')%></a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="<%= main_contact_path %>"><%=t('.header_contact')%></a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="<%= main_about_path %>"><%=t('.header_about')%></a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="<%= products_path %>"><%=t('.header_products')%></a>
        </li>
        <% if user_logged_in %>
          <li class="nav-item">
            <a class="nav-link" href="<%= user_account_path %>"><%=t('.header_account')%></a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="<%= reviews_path %>"><%=t('.header_review')%></a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="<%= orders_path %>"><%=t('.header_order')%></a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="<%= user_logout_path %>"><%=t('.header_logout')%></a>
          </li>
        <% else %>
          <li class="nav-item mr-sm-2">
            <a class="nav-link" href="<%= user_login_path %>"><%=t('.header_login')%></a>
          </li>
        <% end %>
        <li class="nav-item">
          <%# Even though it says Basket, we are actually showing the contents in index Items %>
          <a href="<%= baskets_path %>/<%= session[:basket_id] %>" class="btn btn-outline-warning">Basket <span class="badge badge-light"><%= count_basket() %></span></a>
        </li>
      </ul>
    </div>
  </nav>