config/routes.rb
Rails.application.routes.draw do

  # Establish route URL to these controller/view
  get 'main/home'
  get 'main/about'
  get 'main/contact'

 # Standardise the related routes below
  get 'user/signup', to: 'users#signup'
  get 'user/login', to: 'sessions#login'
  get 'user/account', to: 'users#account'
  get 'user/logout', to: 'sessions#destroy'
  get 'user/edit', to: 'users#edit'

  delete 'remove_item', to: 'items#remove_item'

  get 'checkout/details', to: 'customer_infos#new'
  get 'checkout/details/order', to: 'orders#new'

  # Contact form that uses mailer to send email (if it was linked to SMTP server)
  get 'contacts/form'

  # Reroutes contacts_request_form to request_form - used for POST method only
  post 'request_form', to:'contacts#request_form'

  # Get all the appropriate CRUD paths/routes for our resources
  resources :users, only: [:create, :edit, :update, :signup, :account]
  resources :sessions, only: [:create, :login, :destroy]
  # User Reviews should be nested to products (as reviews should be created on products)
  resources :products, only: [:index, :show] do
    resources :reviews, only: [:new]
  end

  resources :reviews, only: [:index, :show, :edit, :destroy, :create, :update]

  resources :baskets, only: [:index, :show, :create, :destroy]
  resources :items, only: [:index, :create, :remove_item]
  resources :orders, only: [:index, :show, :new, :create]
  resources :customer_infos, only: [:index, :show, :new, :edit, :create, :update]

  # This is the first page the user will first load into as it is the root page
  root 'main#home'

  # We don't want those pesky unknown routes disturbing our user experience - redirects all unknown routes to root_path
  match '*path' => redirect('/'), via: :get
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/product.rb
class Product < ApplicationRecord
  # Ensures the Price field can only be >= £0 - So third-party listings cannot be free (if this feature is implemented)
  validates :price, numericality: {greater_than_or_equal_to: 0}
  has_many :items, dependent: :restrict_with_error
  has_many :reviews
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def product_params
      params.require(:product).permit(:name, :description, :category, :image_url, :price, :quantityInStock)
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_index.html.erb
<hr>
<h1><%=t('.index_shared_title')%></h1>
<hr>
<br>
<div class="container">
  <% @products.sort_by(&:name).each do |product| %>
    <% if product.has_badge %>
      <div class="row">
        <div class="col-sm-4" align="center">
          <%= render 'shared/badgechoice' %>
          <a href="<%= products_path %>/<%= product.id %>"><img src="<%= asset_path(product.image_url)%>" alt="<%= product.name %>" class="img-large"></a>
        </div>
        <div class="col-sm-8">
          <h2><%= link_to product.name, product %>
            <% if product.is_new %>
              <%= render 'shared/badgenew' %>
            <% end %>
          </h2>
          <% if Review.exists?(product_id: product.id) %>
          <% @averageRating = Review.where(product_id: product.id).average(:rating) %>
          <% else %>
          <% @averageRating = 0 %>
          <% end %>
          <div class="rating-review-stars" style="--rating: <%= @averageRating %>;" title="<%=t('.index_reviewstars_title1')%> <%= @averageRating %> <%=t('.index_reviewstars_title2')%>"></div>
          <p><%=t('.index_category_label')%>
            <i><%= product.category %></i>
          </p>
          <h4><%=t('.index_price_sign')%><%= product.price %></h4>
          <a href="<%= products_path %>/<%= product.id %>" class="btn btn-primary"><%=t('.index_buy_button')%></a>
        </div>
      </div>
      <hr>
    <% end %>
  <% end %>
</div>
<br>

app/views/products/index.html.erb
<br>
<h1><%=t('.index_title')%></h1>
<hr>
<br>
<div class="container">
  <% @products.sort_by(&:name).each do |product| %>
    <div class="row">
      <div class="col-sm-4" align="center">
        <% if product.has_badge %>
          <%= render 'shared/badgechoice' %>
        <% end %>
        <a href="<%= products_path %>/<%= product.id %>"><img src="<%= asset_path(product.image_url)%>" alt="<%= product.name %>" class="img-large"></a>
      </div>
      <div class="col-sm-8">
        <h2><%= link_to product.name, product %>
          <% if product.is_new %>
            <%= render 'shared/badgenew' %>
          <% end %>
        </h2>
        <% if Review.exists?(product_id: product.id) %>
        <% @averageRating = Review.where(product_id: product.id).average(:rating) %>
        <% else %>
        <% @averageRating = 0 %>
        <% end %>
        <div class="rating-review-stars" style="--rating: <%= @averageRating %>;" title="<%=t('.index_reviewstars_title1')%> <%= @averageRating %> <%=t('.index_reviewstars_title2')%>"></div>
        <p><%=t('.index_category_label')%>
          <i><%= product.category %></i>
        </p>
        <h4><%=t('.index_price_sign')%><%= product.price %></h4>
        <a href="<%= products_path %>/<%= product.id %>" class="btn btn-primary"><%=t('.index_buy_button')%></a>
      </div>
    </div>
    <hr>
  <% end %>
  <br>
</div>

app/views/products/show.html.erb
<%= render 'shared/flashmessage' %>

<div class="container-fluid">
  <div class="row">
    <div class="col-sm-6" align="center">
      <img src="<%= asset_path(@product.image_url)%>" alt="<%= @product.name %>" class="img-display">
    </div>
    <div class="col-sm-5">
      <br>
      <h1><%= @product.name %>
        <% if @product.is_new %>
          <%= render 'shared/badgenew' %>
        <% end %>
      </h1>
      <% if Review.exists?(product_id: @product.id) %>
      <% @averageRating = Review.where(product_id: @product.id).average(:rating) %>
      <% else %>
      <% @averageRating = 0 %>
      <% end %>
      <div class="rating-review-stars" style="--rating: <%= @averageRating %>;" title="<%=t('.show_reviewstars_title1')%> <%= @averageRating %> <%=t('.show_reviewstars_title2')%>"></div>
      <br>
      <% if @product.has_badge %>
        <%= render 'shared/badgechoice' %>
      <% end %>
      <hr>
      <h3><%=t('.show_price')%>
        <%=t('.show_currency')%><%= @product.price %></h3>
      <br>
      <h4><%=t('.show_quantityinstock')%>
        <%= @product.quantityInStock %></h4>
      <hr>
      <p>
        <b><%=t('.show_description')%></b>
      </p>
      <hr>
      <p><%= @product.description %></p>
      <p>
        <b><%=t('.show_category')%></b>
        <%= @product.category %></p>
      <hr>
        <%= button_to t('.show_add_to_basket'), items_path(product_id: @product.id), params: { quantityOrdered: '1'}, class: "btn btn-primary" %>
      <br>
      <%= link_to 'Back', :back %>
    </div>
  </div>
</div>

<hr>

<%= button_to 'Write a Review', new_product_review_path(product_id: @product.id), method: :get, class: "btn btn-primary" %>

<%= render 'reviews/index' %>