config/routes.rb
Rails.application.routes.draw do

  # Establish route URL to these controller/view
  get 'main/home'
  get 'main/about'
  get 'main/contact'

 # Standardise the related routes below
  get 'user/signup', to: 'users#signup'
  get 'user/login', to: 'sessions#login'
  get 'user/account', to: 'users#account'
  get 'user/logout', to: 'sessions#destroy'
  get 'user/edit', to: 'users#edit'

  delete 'remove_item', to: 'items#remove_item'

  get 'checkout/details', to: 'customer_infos#new'
  get 'checkout/details/order', to: 'orders#new'

  # Contact form that uses mailer to send email (if it was linked to SMTP server)
  get 'contacts/form'

  # Reroutes contacts_request_form to request_form - used for POST method only
  post 'request_form', to:'contacts#request_form'

  # Get all the appropriate CRUD paths/routes for our resources
  resources :users, only: [:create, :edit, :update, :signup, :account]
  resources :sessions, only: [:create, :login, :destroy]
  # User Reviews should be nested to products (as reviews should be created on products)
  resources :products, only: [:index, :show] do
    resources :reviews, only: [:new]
  end

  resources :reviews, only: [:index, :show, :edit, :destroy, :create, :update]

  resources :baskets, only: [:index, :show, :create, :destroy]
  resources :items, only: [:index, :create, :remove_item]
  resources :orders, only: [:index, :show, :new, :create]
  resources :customer_infos, only: [:index, :show, :new, :edit, :create, :update]

  # This is the first page the user will first load into as it is the root page
  root 'main#home'

  # We don't want those pesky unknown routes disturbing our user experience - redirects all unknown routes to root_path
  match '*path' => redirect('/'), via: :get
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_review, only: [:show, :edit, :update, :destroy]

  # GET /reviews
  # GET /reviews.json
  def index
    if user_logged_in
      #@reviews = Review.all
      @reviews = Review.where(user_id: session[:user_id]).order("created_at ASC")

      if session[:user_id] == 0
        @reviews = Review.all
      end

    else
      flash[:alert] = "Login to your account to see your reviews."
      redirect_to root_path
    end
  end

  # GET /reviews/1
  # GET /reviews/1.json
  def show
    if !(user_logged_in)
      flash[:alert] = "You do not have permission to view this."
      redirect_to root_path
    end
  end

  # GET /reviews/new
  def new
    if user_logged_in
      # Make sure that a User can only have one Review per Product
      @product = Product.find(params[:product_id])
      if Review.exists?(product_id: @product.id, user_id: session[:user_id])
        flash[:alert] = "You've already made a review of Product ID " + @product.id.inspect + "."
        redirect_to reviews_path
      else
        @review = Review.new
      end
    else
      flash[:alert] = "You need to be logged in to write a review."
      redirect_to root_path
    end
  end

  # GET /reviews/1/edit
  def edit
    if user_logged_in
      @currentReview = Review.find(params[:id])

      if !(@currentReview.user_id == session[:user_id])
        flash[:alert] = "This review does not belong to you."
        redirect_to reviews_path
      end

    else
      flash[:alert] = "You need to be logged in to edit a review."
      redirect_to root_path
    end
  end

  # POST /reviews
  # POST /reviews.json
  def create
    @product = Product.find(params[:review][:product_id])
    params[:review][:user_id] = session[:user_id]

    # The additional check if the User purposefully tries to change the hidden field product_id value in the form creation
    if Review.exists?(product_id: @product.id, user_id: session[:user_id])
      flash[:alert] = "You've already made a review of Product ID " + @product.id.inspect + "."
      redirect_to reviews_path
    else
      @review = Review.new(review_params)

      respond_to do |format|
        if @review.save
          format.html { redirect_to @product, notice: 'Review was successfully created.' }
          format.json { render :show, status: :created, location: @review }
        else
          format.html { render :new }
          format.json { render json: @review.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  # PATCH/PUT /reviews/1
  # PATCH/PUT /reviews/1.json
  def update
    @review = Review.find(params[:id])
    @product = Product.find(@review.product_id)

    params[:review][:product_id] = @product.id

    respond_to do |format|
      if @review.update(review_params)
        format.html { redirect_to reviews_path, notice: 'Review was successfully updated.' }
        format.json { render :show, status: :ok, location: @review }
      else
        format.html { render :edit }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reviews/1
  # DELETE /reviews/1.json
  def destroy
    @review.destroy
    respond_to do |format|
      format.html { redirect_to reviews_url, notice: 'Review was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_review
      if params[:id] != nil && Review.exists?(params[:id])
        @review = Review.find(params[:id])
      end
    end

    # Only allow a list of trusted parameters through.
    def review_params
      params.require(:review).permit(:product_id, :user_id, :title, :comment, :rating)
    end
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/reviews/_form.html.erb
<div class="center-content-review">
<%= form_with(model: review, local: true) do |form| %>
  <% if review.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(review.errors.count, "error") %> prohibited this review from being saved:</h2>

      <ul>
      <% review.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%# A User can perform an ugly hack, where they can change the hidden product_id value to any value they desire %>
    <%# This is bad because a User should only be able to write one review once per product %>
    <%# Additional checks are added in the reviews controller %>
    <%= hidden_field(:review, :product_id, :value => params[:product_id]) %>
  </div>

  <div class="field">
    <%= form.label :title, t(".form_title_label") %><br>
    <%= form.text_field :title, title: t(".form_title_title"), size: 30, :required => true %>
  </div>

  <br>
  <div class="field">
    <%= form.label :comment, t(".form_comment_label") %><br>
    <%= form.text_area :comment, title: t(".form_comment_title"), placeholder: t(".form_comment_placeholder"), size: "30x5", :required => true %>
  </div>

  <br>
  <div class="field">
    <%= form.label :rating, t(".form_rating_label") %><br>
    <%= form.number_field :rating, min: 1, max: 5, size: 2, :required => true %>
  </div>

  <br>
  <div class="actions">
    <%= form.submit%>
  </div>
<% end %>
</div>

app/views/reviews/_index.html.erb
<%# This index displays the User reviews for the appropriate product page %>
<hr>
<% @reviews = Review.where(product_id: @product.id) %>

<div class="container">
  <% @reviews.sort_by(&:created_at).each do |review| %>

  <div class="row comment-left-border">
    <div class="col-sm-4" align="left">
      <p><strong><%= review.user.username %></strong> <i>says:</i></p>
    </div>
  </div>

  <div class="row comment-left-border">
    <div class="col-sm-2" align="left">
      <div class="rating-review-stars" style="--rating: <%= review.rating %>;" title="<%=t('.index_reviewstars_title1')%> <%= review.rating %> <%=t('.index_reviewstars_title2')%>"></div>
    </div>

    <div class="col-sm-4" align="left">
      <p><strong><%= review.title %></strong></p>
    </div>

  </div>

  <div class="row comment-left-border">
    <div class="col-sm-4" align="left">
        <p><strong>Reviewed on:</strong> <%= review.created_at %></p>
    </div>
  </div>

  <div class="row comment-left-border">
    <div class="col-sm-8" align="left">
      <p><%= review.comment %></p>
    </div>
  </div>

  <hr>
  <% end %>
</div>

<br>

app/views/reviews/edit.html.erb
<br>
<h1><%=t('.edit_title')%></h1>
<hr>

<%= render 'form', review: @review %>

<%= link_to 'Show', @review %> |
<%= link_to 'Back', reviews_path %>

app/views/reviews/index.html.erb
<%= render 'shared/flashmessage' %>

<br>
<h1><%=t('.index_title')%></h1>
<hr>

<div class="container">
  <div class="row">
    <div class="col-sm-2" align="center">
      <span>
        <b><%=t('.index_productID_column')%></b>
      </span>
    </div>

    <div class="col-sm-3" align="center">
      <span>
        <b><%=t('.index_reviewTitle_column')%></b>
      </span>
    </div>

    <div class="col-sm-1" align="center">
      <span>
        <b><%=t('.index_rating_column')%></b>
      </span>
    </div>

    <div class="col-sm-2" align="center">
      <span>
        <b><%=t('.index_updatedAt_column')%></b>
      </span>
    </div>

    <div class="col-sm-1" align="center">
    </div>

    <div class="col-sm-1" align="center">
    </div>

    <div class="col-sm-1" align="center">
    </div>

  </div>
  <hr>

  <% if @reviews != nil && @reviews.count > 0 %>
    <% @reviews.each do |review| %>
      <div class="row">

        <div class="col-sm-2" align="center">
          <%= review.product.id %>
        </div>

        <div class="col-sm-3" align="center">
          <%= review.title %>
        </div>

        <div class="col-sm-1" align="center">
          <%= review.rating %>
        </div>

        <div class="col-sm-2" align="center">
          <%= review.updated_at %>
        </div>

        <div class="col-sm-1" align="center">
          <%= link_to 'Show', review %>
        </div>

        <div class="col-sm-1" align="center">
          <%= link_to 'Edit', edit_review_path(review) %>
        </div>

        <div class="col-sm-1" align="center">
          <%= link_to 'Destroy', review, method: :delete, data: { confirm: 'Are you sure?' } %>
        </div>

      </div>
      <br>
    <% end %>
    <hr>
    <%= link_to t('.index_linkto_message1'), products_path %>
    <br>
    <br>
  <% else %>
  <%= link_to t('.index_linkto_message2'), products_path %>
  <% end %>

</div>

app/views/reviews/new.html.erb
<br>
<h1><%=t('.new_title')%></h1>
<hr>

<%= render 'form', review: @review %>

<%= link_to 'Back', reviews_path %>

app/views/reviews/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Product ID:</strong>
  <%= @review.product.id %>
</p>

<p>
  <strong>User ID:</strong>
  <%= @review.user.id %>
</p>

<p>
  <strong>Title:</strong>
  <%= @review.title %>
</p>

<p>
  <strong>Comment:</strong>
  <%= @review.comment %>
</p>

<p>
  <strong>Rating:</strong>
  <%= @review.rating %>
</p>

<%= link_to 'Edit', edit_review_path(@review) %> |
<%= link_to 'Back', reviews_path %>